site_name: John Laudun

nav:
    - Home: index.md
    - Vita: vita.md
    - Research Statement: research.md
    - Teaching Statement: teaching.md
    - Diversity Statement: diversity.md
    - About: about.md

theme:
    name: null
    custom_dir: 'julienne/'

markdown_extensions:
    - smarty
